### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by ssnake** [vt-vl-lab/3d-photo-inpainting#23]
Hye guys,

Trying to set up stuff via docker. Bumped into issue:

```
>docker-compose up
3d_1  | Traceback (most recent call last):
3d_1  |   File "main.py", line 28, in <module>
3d_1  |     vispy.use(app='egl')
3d_1  |   File "/opt/conda/lib/python3.7/site-packages/vispy/util/wrappers.py", line 97, in use
3d_1  |     use_app(app)
3d_1  |   File "/opt/conda/lib/python3.7/site-packages/vispy/app/_default_app.py", line 47, in use_app
3d_1  |     default_app = Application(backend_name)
3d_1  |   File "/opt/conda/lib/python3.7/site-packages/vispy/app/application.py", line 49, in __init__
3d_1  |     self._use(backend_name)
3d_1  |   File "/opt/conda/lib/python3.7/site-packages/vispy/app/application.py", line 235, in _use
3d_1  |     raise RuntimeError(msg)
3d_1  | RuntimeError: Could not import backend "EGL":
3d_1  | Could not initialize

```

My Dockerfile

```
FROM pytorch/pytorch:1.4-cuda10.1-cudnn7-runtime

COPY . /app/
WORKDIR /app

RUN pip install -r requirements.txt
RUN apt update
RUN apt install -y wget 
RUN apt install -y libfontconfig1-dev
RUN pip install scipy matplotlib scikit-image
RUN apt install -y ffmpeg git less nano libsm6 libxext6 libxrender-dev python3-pyqt4 libgegl-0.3-0 libegl1 libegl-mesa0 libegl1-mesa-dev libgegl-dev
```
docker-compose.yml

```yaml
version: '2.3'

services:
  3d:
    build: .
    volumes: 
      - .:/app
      - .torch:/root/.torch
    working_dir: /app
    networks:                                                                                                                                          
     - withvpn
    stdin_open: true
    tty: true
    runtime: nvidia
    ipc: host
    environment:
      - CUDA_VISIBLE_DEVICES=0
    command: python main.py --config argument.yml
networks:                                                                                                                                              
  withvpn:                                                                                                                                             
    ipam:                                                                                                                                              
      config:                                                                                                                                          
      - subnet: 170.13.241.0/24                                                                                                                        
        gateway: 170.13.241.1

```

**Comment by ssnake** [comment]
```python
>>> import vispy; print(vispy.sys_info())
Platform: Linux-4.15.0-96-generic-x86_64-with-debian-buster-sid
Python:   3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]
NumPy:    1.17.4
App info-gathering error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/vispy/util/config.py", line 422, in sys_info
    app = use_app(call_reuse=False)  # suppress messages
  File "/opt/conda/lib/python3.7/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/opt/conda/lib/python3.7/site-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/opt/conda/lib/python3.7/site-packages/vispy/app/application.py", line 256, in _use
    'PyQt' % [b[0] for b in CORE_BACKENDS])
RuntimeError: Could not import any of the backends. You need to install any of ['PyQt4', 'PyQt5', 'PySide', 'PySide2', 'Pyglet', 'Glfw', 'SDL2', 'wx', 'EGL', 'osmesa']. We recommend PyQt

```

**Comment by ssnake** [comment]
Working docker stuff:

Dockerfile

```
FROM pytorch/pytorch:1.4-cuda10.1-cudnn7-runtime

COPY . /app/
WORKDIR /app
RUN apt update
RUN apt install -y libfontconfig1-dev wget ffmpeg libsm6 libxext6 libxrender-dev mesa-utils-extra libegl1-mesa-dev libgles2-mesa-dev xvfb
ENV DISPLAY=:0
RUN pip install -r requirements.txt

RUN pip install scipy matplotlib scikit-image
```

docker-compose.yaml:
```
version: '2.3'

services:
  3d:
    build: .
    volumes: 
      - .:/app
      - .torch:/root/.torch
    working_dir: /app
    stdin_open: true
    tty: true
    runtime: nvidia
    ipc: host
    environment:
      - CUDA_VISIBLE_DEVICES=0
    command: ./start.sh

```
start.sh:

```
#!/bin/sh
Xvfb :0 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
python -c "import vispy; print(vispy.sys_info())"
python main.py --config argument.yml
```

To make magic happen type in same folder
```
> docker-compose up
```
